services:
  - type: web
    name: astra-lens
    env: python
    buildCommand: "pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install -r backend/requirements.txt && cd frontend && npm install && npm run build && cd .."
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: Yashashvi@7136
